"""Writes to IcebergCompatV1/V2 (UniForm) tables and to `geospatial` tables.

delta-kernel 0.28 refuses to write IcebergCompatV1/V2 (it writes V3, whose
rules include V2's) and cannot convert GEOMETRY/GEOGRAPHY to Arrow at all.
Here both are written through the kernel, each keeping the protocol's rules,
or refused when the write is planned:

* IcebergCompatV1/V2: partition values materialized in every data file, Parquet
  field ids for list elements and map keys and values, `numRecords` in every
  add, no deletion vectors, no schema change the Iceberg conversion cannot
  follow. A UniForm table (Iceberg metadata generated by Databricks) is written
  only as `ds.connect(uniform_writes=)` says.
* geospatial: WKB binary columns, typed GEOMETRY/GEOGRAPHY in Parquet, with
  no min/max statistics for them; the log keeps the table's own geo types.

The tables' logs are written as Databricks leaves them (see
tests/live/interop.py for the same checks against Databricks itself).
"""

from __future__ import annotations

import glob
import json
import os
import pickle
import struct
from typing import Any

import pyarrow as pa
import pyarrow.parquet as pq
import pytest
from deltaswamp.errors import DeltaSwampWarning, InvalidArgumentError, UnreachableTableError

from tests.integration.test_table_feature_writes import _commit, _parquet, _worker


def _log(
    path: str, protocol: dict[str, Any], fields: list[Any], partitions: list[str], **config: str
) -> None:
    os.makedirs(os.path.join(path, "_delta_log"))
    actions = [
        {"commitInfo": {"timestamp": 1, "operation": "CREATE TABLE"}},
        {"protocol": protocol},
        {
            "metaData": {
                "id": "5b3c0a1e-0000-4000-8000-0000000000cc",
                "format": {"provider": "parquet", "options": {}},
                "schemaString": json.dumps({"type": "struct", "fields": fields}),
                "partitionColumns": partitions,
                "configuration": config,
                "createdTime": 1,
            }
        },
    ]
    with open(os.path.join(path, "_delta_log", f"{0:020d}.json"), "w") as fh:
        fh.write("\n".join(json.dumps(a) for a in actions) + "\n")


def _mapped(
    name: str, type_: Any, cid: int, nested: dict[str, int] | None = None
) -> dict[str, Any]:
    physical = f"col-{cid}"
    metadata: dict[str, Any] = {
        "delta.columnMapping.id": cid,
        "delta.columnMapping.physicalName": physical,
    }
    if nested is not None:
        metadata["delta.columnMapping.nested.ids"] = {
            f"{physical}.{k}": v for k, v in nested.items()
        }
    return {"name": name, "type": type_, "nullable": True, "metadata": metadata}


# ---------------------------------------------------------------- IcebergCompat


def _v2_table(path: str, **config: str) -> None:
    """An IcebergCompatV2 table as Databricks creates it (name mapping, nested ids)."""
    _log(
        path,
        {
            "minReaderVersion": 2,
            "minWriterVersion": 7,
            "writerFeatures": ["columnMapping", "icebergCompatV2", "appendOnly", "invariants"],
        },
        [
            _mapped("id", "long", 1, {}),
            _mapped(
                "a",
                {"type": "array", "elementType": "integer", "containsNull": True},
                2,
                {"element": 5},
            ),
            _mapped(
                "m",
                {
                    "type": "map",
                    "keyType": "string",
                    "valueType": "integer",
                    "valueContainsNull": True,
                },
                3,
                {"key": 6, "value": 7},
            ),
            _mapped("p", "string", 4, {}),
        ],
        ["p"],
        **{
            "delta.enableIcebergCompatV2": "true",
            "delta.columnMapping.mode": "name",
            "delta.columnMapping.maxColumnId": "7",
            **config,
        },
    )


def _v2_rows(ids: list[int], part: str) -> pa.Table:
    return pa.table(
        {
            "id": pa.array(ids, pa.int64()),
            "a": pa.array([[i, i + 1] for i in ids], pa.list_(pa.int32())),
            "m": pa.array([[("k", i)] for i in ids], pa.map_(pa.string(), pa.int32())),
            "p": pa.array([part] * len(ids)),
        }
    )


def _field_ids(file: str) -> dict[str, int]:
    """Every Parquet field's dotted path -> field id, as a reader resolves them."""
    out: dict[str, int] = {}
    arrow = pq.ParquetFile(file).schema_arrow

    def visit(field: Any, path: str) -> None:
        md = field.metadata or {}
        if b"PARQUET:field_id" in md:
            out[path] = int(md[b"PARQUET:field_id"])
        t = field.type
        if pa.types.is_list(t):
            visit(t.value_field, f"{path}.element")
        elif pa.types.is_map(t):
            visit(t.key_field, f"{path}.key")
            visit(t.item_field, f"{path}.value")
        elif pa.types.is_struct(t):
            for i in range(t.num_fields):
                visit(t.field(i), f"{path}.{t.field(i).name}")

    for f in arrow:
        visit(f, f.name)
    return out


class TestIcebergCompatV2:
    def test_every_write_path_keeps_the_writer_rules(self, conn: Any, tmp_path: Any) -> None:
        path = str(tmp_path / "t")
        _v2_table(path)
        before = _parquet(path)
        conn.open_table(path).append(_v2_rows([1, 2], "x"))
        plan = conn.open_table(path).plan_write()
        plan.commit([_worker(plan).write(_v2_rows([3, 4], "y"))])
        conn.open_table(path).delete("id = 2")
        conn.open_table(path).update({"id": "id + 100"}, predicate="id = 3")
        rows = conn.open_table(path).to_arrow().to_pylist()
        assert sorted((r["id"], r["p"]) for r in rows) == [(1, "x"), (4, "y"), (103, "y")]
        files = _parquet(path) - before
        assert files
        for file in files:
            ids = _field_ids(file)
            # Column mapping ids, and the nested ids Iceberg resolves by.
            assert ids["col-1"] == 1 and ids["col-2"] == 2 and ids["col-3"] == 3
            assert ids["col-2.element"] == 5
            assert ids["col-3.key"] == 6 and ids["col-3.value"] == 7
            # The partition value is in the file too.
            assert ids["col-4"] == 4
            # Timestamps would be INT64; none here, and none INT96 anywhere.
            assert "INT96" not in str(pq.ParquetFile(file).schema)
        adds = [a["add"] for v in range(1, 5) for a in _commit(path, v) if "add" in a]
        assert adds and all(json.loads(a["stats"])["numRecords"] >= 0 for a in adds)
        # Copy-on-write: no deletion vector anywhere.
        assert all(a.get("deletionVector") is None for a in adds)

    def test_compaction_keeps_them_too(self, conn: Any, tmp_path: Any) -> None:
        path = str(tmp_path / "t")
        _v2_table(path)
        for i in range(3):
            conn.open_table(path).append(_v2_rows([i], "x"))
        before = _parquet(path)
        conn.open_table(path).optimize()
        new = _parquet(path) - before
        assert new and all(_field_ids(f)["col-4"] == 4 for f in new)

    def test_schema_changes_are_refused_before_writing(self, conn: Any, tmp_path: Any) -> None:
        path = str(tmp_path / "t")
        _v2_table(path)
        t = conn.open_table(path)
        assert not t.can("add_column")
        assert "IcebergCompatV2" in t.can("add_column").reason
        wider = _v2_rows([1], "x").append_column("z", pa.array([1], pa.int64()))
        with pytest.raises(UnreachableTableError, match="schema"):
            t.append(wider, schema_mode="merge")
        # Metadata changes are Databricks' to make, which keeps the Iceberg
        # conversion in step with them.
        assert not t.can("set_properties", properties={"delta.enableDeletionVectors": "true"})

    def test_a_table_breaking_the_rules_is_refused(self, conn: Any, tmp_path: Any) -> None:
        path = str(tmp_path / "t")
        _v2_table(path, **{"delta.enableDeletionVectors": "true"})
        verdict = conn.open_table(path).can("append")
        assert not verdict.ok and "deletion vectors" in verdict.reason


class TestIcebergCompatV1:
    def _table(self, path: str, fields: list[Any]) -> None:
        _log(
            path,
            {
                "minReaderVersion": 2,
                "minWriterVersion": 7,
                "writerFeatures": ["columnMapping", "icebergCompatV1"],
            },
            fields,
            ["p"],
            **{
                "delta.enableIcebergCompatV1": "true",
                "delta.columnMapping.mode": "name",
                "delta.columnMapping.maxColumnId": "3",
            },
        )

    def test_partition_values_follow_the_data_columns(self, conn: Any, tmp_path: Any) -> None:
        path = str(tmp_path / "t")
        self._table(
            path, [_mapped("id", "long", 1), _mapped("s", "string", 2), _mapped("p", "string", 3)]
        )
        conn.open_table(path).append(
            pa.table({"id": pa.array([1], pa.int64()), "s": ["a"], "p": ["x"]})
        )
        (file,) = _parquet(path)
        assert pq.ParquetFile(file).schema_arrow.names == ["col-1", "col-2", "col-3"]

    def test_a_partition_column_before_the_data_is_refused(self, conn: Any, tmp_path: Any) -> None:
        path = str(tmp_path / "t")
        self._table(
            path, [_mapped("p", "string", 3), _mapped("id", "long", 1), _mapped("s", "string", 2)]
        )
        verdict = conn.open_table(path).can("append")
        assert not verdict.ok and "after the data columns" in verdict.reason


class TestUniForm:
    def _table(self, path: str) -> None:
        _v2_table(path, **{"delta.universalFormat.enabledFormats": "iceberg"})

    def test_refused_unless_the_connection_says_what_to_do(self, conn: Any, tmp_path: Any) -> None:
        path = str(tmp_path / "t")
        self._table(path)
        verdict = conn.open_table(path).can("append")
        assert not verdict.ok and "uniform_writes" in verdict.reason

    def test_stale_writes_and_warns(self, tmp_path: Any) -> None:
        import deltaswamp as ds

        path = str(tmp_path / "t")
        self._table(path)
        conn = ds.connect(uniform_writes="stale")
        with pytest.warns(DeltaSwampWarning, match="Iceberg readers"):
            conn.open_table(path).append(_v2_rows([1], "x"))
        assert conn.open_table(path).to_arrow().num_rows == 1
        # VACUUM would delete files a stale Iceberg snapshot may still read.
        assert not conn.open_table(path).can("vacuum")

    def test_sync_needs_the_warehouse(self, tmp_path: Any) -> None:
        import deltaswamp as ds

        path = str(tmp_path / "t")
        self._table(path)
        verdict = ds.connect(uniform_writes="sync").open_table(path).can("append")
        assert not verdict.ok and "SQL warehouse" in verdict.reason

    def test_sync_regenerates_after_every_commit(
        self, tmp_path: Any, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        import deltaswamp as ds
        from deltaswamp.router import Router
        from deltaswamp.table import Table

        path = str(tmp_path / "t")
        self._table(path)
        synced: list[str] = []
        monkeypatch.setattr(Router, "uniform_sync_reachable", lambda self, table: True)
        monkeypatch.setattr(Table, "sync_iceberg", lambda self: synced.append("sync"))
        conn = ds.connect(uniform_writes="sync")
        conn.open_table(path).append(_v2_rows([1], "x"))
        conn.open_table(path).delete("id = 1")
        plan = conn.open_table(path).plan_write()
        plan.commit([_worker(plan).write(_v2_rows([2], "y"))])
        assert synced == ["sync", "sync", "sync"]

    def test_the_mode_is_checked(self) -> None:
        import deltaswamp as ds

        with pytest.raises(InvalidArgumentError, match="uniform_writes"):
            ds.connect(uniform_writes="yes")


# ---------------------------------------------------------------- geospatial


def _point(x: float, y: float) -> bytes:
    return struct.pack("<BIdd", 1, 1, x, y)


def _geo_table(path: str, fields: list[Any] | None = None) -> None:
    """A geospatial table as Databricks creates it."""
    _log(
        path,
        {
            "minReaderVersion": 3,
            "minWriterVersion": 7,
            "readerFeatures": ["deletionVectors", "geospatial"],
            "writerFeatures": ["deletionVectors", "geospatial", "appendOnly", "invariants"],
        },
        fields
        or [
            {"name": "id", "type": "long", "nullable": True, "metadata": {}},
            {"name": "g", "type": "geometry(OGC:CRS84)", "nullable": True, "metadata": {}},
            {
                "name": "h",
                "type": "geography(OGC:CRS84, SPHERICAL)",
                "nullable": True,
                "metadata": {},
            },
        ],
        [],
        **{"delta.enableDeletionVectors": "true"},
    )


def _geo_rows(ids: list[int]) -> pa.Table:
    return pa.table(
        {
            "id": pa.array(ids, pa.int64()),
            "g": pa.array([_point(i, i + 1) for i in ids], pa.binary()),
            "h": pa.array([_point(i, -i) for i in ids], pa.binary()),
        }
    )


class TestGeospatial:
    def test_written_as_typed_wkb_and_read_back(self, conn: Any, tmp_path: Any) -> None:
        path = str(tmp_path / "t")
        _geo_table(path)
        conn.open_table(path).append(_geo_rows([1, 2]))
        plan = conn.open_table(path).plan_write()
        plan.commit([_worker(plan).write(_geo_rows([3]))])
        table = conn.open_table(path).to_arrow()
        assert sorted(table.column("id").to_pylist()) == [1, 2, 3]
        got = {r["id"]: r["g"] for r in table.to_pylist()}
        assert got[2] == _point(2, 3)
        # The column says what it holds.
        assert (
            table.schema.field("g").metadata[b"deltaswamp.geospatial.type"]
            == b"geometry(OGC:CRS84)"
        )
        for file in _parquet(path):
            text = str(pq.ParquetFile(file).schema)
            assert "Geometry(crs=OGC:CRS84)" in text
            assert "Geography(crs=OGC:CRS84, algorithm=spherical)" in text
        for v in (1, 2):
            for action in _commit(path, v):
                if "add" in action:
                    stats = json.loads(action["add"]["stats"])
                    assert "g" not in stats.get("minValues", {})
                    assert stats["nullCount"]["g"] == 0

    def test_the_log_keeps_the_geo_types(self, conn: Any, tmp_path: Any) -> None:
        path = str(tmp_path / "t")
        _geo_table(path)
        conn.open_table(path).append(_geo_rows([1]))
        t = conn.open_table(path)
        t.checkpoint()
        engine = conn.router.engines[__import__("deltaswamp").capability.Engine.KERNEL]
        schema = json.loads(
            json.loads(engine.snapshot(t._enrich()).metadata_json())["schemaString"]
        )
        assert [f["type"] for f in schema["fields"]][1:] == [
            "geometry(OGC:CRS84)",
            "geography(OGC:CRS84, SPHERICAL)",
        ]
        # The checkpoint holds the table's own metadata and protocol.
        checkpoint = glob.glob(os.path.join(path, "_delta_log", "*.checkpoint.parquet"))
        assert checkpoint
        raw = pq.read_table(checkpoint[0]).to_pylist()
        logged = [r["metaData"] for r in raw if r.get("metaData")]
        assert "geometry(OGC:CRS84)" in logged[0]["schemaString"]
        protocol = next(r["protocol"] for r in raw if r.get("protocol"))
        assert "geospatial" in protocol["readerFeatures"]

    def test_deletion_vectors_and_rewrites(self, conn: Any, tmp_path: Any) -> None:
        path = str(tmp_path / "t")
        _geo_table(path)
        conn.open_table(path).append(_geo_rows([1, 2, 3]))
        conn.open_table(path).delete("id = 2")
        conn.open_table(path).update({"id": "id + 10"}, predicate="id = 3")
        rows = conn.open_table(path).to_arrow().to_pylist()
        assert sorted((r["id"], r["g"]) for r in rows) == [(1, _point(1, 2)), (13, _point(3, 4))]

    def test_what_is_refused(self, conn: Any, tmp_path: Any) -> None:
        path = str(tmp_path / "t")
        _geo_table(path)
        t = conn.open_table(path)
        assert not t.can("add_column")
        wider = _geo_rows([1]).append_column("z", pa.array([1], pa.int64()))
        with pytest.raises(UnreachableTableError, match="schema"):
            t.append(wider, schema_mode="merge")

    def test_geo_inside_an_array_is_read_but_not_written(self, conn: Any, tmp_path: Any) -> None:
        path = str(tmp_path / "t")
        _geo_table(
            path,
            [
                {"name": "id", "type": "long", "nullable": True, "metadata": {}},
                {
                    "name": "gs",
                    "type": {
                        "type": "array",
                        "elementType": "geometry(OGC:CRS84)",
                        "containsNull": True,
                    },
                    "nullable": True,
                    "metadata": {},
                },
            ],
        )
        t = conn.open_table(path)
        assert t.can("scan")
        verdict = t.can("append")
        assert not verdict.ok and "inside an array or map" in verdict.reason

    def test_the_change_feed_is_refused(self, conn: Any, tmp_path: Any) -> None:
        path = str(tmp_path / "t")
        _geo_table(path)
        with open(os.path.join(path, "_delta_log", f"{1:020d}.json"), "w") as fh:
            meta = _commit(path, 0)[2]
            meta["metaData"]["configuration"]["delta.enableChangeDataFeed"] = "true"
            fh.write(json.dumps(meta) + "\n")
        verdict = conn.open_table(path).can("cdf")
        assert not verdict.ok and "change feed" in verdict.reason


def test_a_plan_pickles_without_the_uniform_hook(conn: Any, tmp_path: Any) -> None:
    path = str(tmp_path / "t")
    _geo_table(path)
    plan = conn.open_table(path).plan_write()
    assert plan.after_commit is not None
    assert pickle.loads(pickle.dumps(plan)).after_commit is None
