"""Every Delta table shape Databricks produces, read and written through deltaswamp.

The live suite in test_live_databricks.py exercises one scratch table. This
module builds one table per shape -- deletion vectors present, column mapping
after renames, liquid clustering, type widening, variant, collations, row
filters, clones, catalog-managed, and so on -- and checks every answer against
the warehouse, which is ground truth for what Databricks considers the table's
contents.

Two kinds of assertion, and the second matters more:

* reads agree with the warehouse, row for row;
* a claim is honest: when `can()` says yes the call succeeds, and when a
  direct engine cannot serve a shape the refusal names why.

Opt-in on top of the live suite, because it creates ~35 tables:

    DELTASWAMP_TEST_MATRIX=1 pytest tests/integration/test_live_matrix.py -v

It needs DELTASWAMP_TEST_WAREHOUSE_ID (the fixtures are built through it) and
creates a staging volume in the target schema for the write tests.
"""

from __future__ import annotations

import concurrent.futures
import contextlib
import os
import time
import uuid
import warnings
from dataclasses import dataclass, field
from typing import Any

import pytest

pa = pytest.importorskip("pyarrow")

import deltaswamp as ds  # noqa: E402
from deltaswamp.capability import Engine, Operation  # noqa: E402

pytestmark = pytest.mark.filterwarnings("ignore::UserWarning")

_BASE = "(id BIGINT, city STRING, amount DOUBLE, ts TIMESTAMP, d DATE)"
_CITIES = ["oslo", "lima", "cairo", "pune", "rome", "kyiv", "baku", "doha"] * 3
_ROWS = ", ".join(
    f"({i}, '{c}', {i * 1.5}, TIMESTAMP'2026-01-0{1 + i % 9} 10:00:00', DATE'2026-02-0{1 + i % 9}')"
    for i, c in enumerate(_CITIES)
)


@dataclass(frozen=True)
class Shape:
    """One table shape: how to build it, and what deltaswamp should make of it."""

    name: str
    statements: tuple[str, ...]
    #: Whether a direct engine (kernel or delta-rs) should serve a plain scan.
    #: None: it may be claimed -- nothing in the log decides it -- but a claimed
    #: read must then agree with the warehouse or fail loudly.
    direct_read: bool | None = True
    #: Whether earlier versions are readable at all. Databricks refuses time
    #: travel on a table with a row filter or column mask.
    time_travel: bool = True
    #: The predicate used to compare filtered reads against the warehouse.
    predicate: str | None = "id < 5"
    #: Exercised by the write tests.
    writes: bool = False
    tags: frozenset[str] = field(default_factory=frozenset)


def _shape(name: str, *statements: str, **kwargs: Any) -> Shape:
    return Shape(name, statements, **kwargs)


def _ins() -> str:
    return f"INSERT INTO {{t}} VALUES {_ROWS}"


SHAPES: list[Shape] = [
    _shape("plain", f"CREATE TABLE {{t}} {_BASE}", _ins(), writes=True),
    _shape(
        "deletion_vectors",
        f"CREATE TABLE {{t}} {_BASE}",
        _ins(),
        "DELETE FROM {t} WHERE id % 3 = 0",
        "UPDATE {t} SET amount = -1 WHERE id = 1",
        writes=True,
    ),
    _shape(
        "legacy_protocol",
        f"CREATE TABLE {{t}} {_BASE} TBLPROPERTIES ('delta.enableDeletionVectors'='false', "
        "'delta.enableRowTracking'='false', 'delta.minReaderVersion'='1', "
        "'delta.minWriterVersion'='2')",
        _ins(),
        "DELETE FROM {t} WHERE id = 2",
    ),
    _shape(
        "partitioned",
        f"CREATE TABLE {{t}} {_BASE} PARTITIONED BY (city)",
        _ins(),
        "DELETE FROM {t} WHERE id = 5",
        writes=True,
    ),
    _shape(
        "liquid",
        f"CREATE TABLE {{t}} {_BASE} CLUSTER BY (id, city)",
        _ins(),
        "OPTIMIZE {t}",
        writes=True,
        tags=frozenset({"clustered"}),
    ),
    _shape("liquid_auto", f"CREATE TABLE {{t}} {_BASE} CLUSTER BY AUTO", _ins()),
    _shape(
        "column_mapping_name",
        f"CREATE TABLE {{t}} {_BASE} TBLPROPERTIES ('delta.columnMapping.mode'='name')",
        _ins(),
        "ALTER TABLE {t} RENAME COLUMN city TO town",
        "ALTER TABLE {t} DROP COLUMN d",
        "ALTER TABLE {t} ADD COLUMN `weird col.name` STRING",
        "UPDATE {t} SET `weird col.name` = 'x' WHERE id < 4",
        writes=True,
    ),
    _shape(
        "column_mapping_id",
        f"CREATE TABLE {{t}} {_BASE} TBLPROPERTIES ('delta.columnMapping.mode'='id')",
        _ins(),
        "ALTER TABLE {t} RENAME COLUMN city TO town",
    ),
    _shape(
        "change_data_feed",
        f"CREATE TABLE {{t}} {_BASE} TBLPROPERTIES ('delta.enableChangeDataFeed'='true')",
        _ins(),
        "UPDATE {t} SET amount = 0 WHERE id < 3",
        "DELETE FROM {t} WHERE id > 20",
        writes=True,
        tags=frozenset({"cdf"}),
    ),
    _shape(
        "identity",
        "CREATE TABLE {t} (id BIGINT GENERATED BY DEFAULT AS IDENTITY, city STRING)",
        "INSERT INTO {t} (city) VALUES ('a'), ('b'), ('c')",
    ),
    _shape(
        "generated_columns",
        "CREATE TABLE {t} (id BIGINT, ts TIMESTAMP, "
        "day DATE GENERATED ALWAYS AS (CAST(ts AS DATE)))",
        "INSERT INTO {t} (id, ts) VALUES (1, TIMESTAMP'2026-01-01 10:00:00'), "
        "(2, TIMESTAMP'2026-01-02 10:00:00')",
    ),
    _shape(
        "check_constraints",
        "CREATE TABLE {t} (id BIGINT NOT NULL, amount DOUBLE)",
        "ALTER TABLE {t} ADD CONSTRAINT positive CHECK (amount > 0)",
        "INSERT INTO {t} VALUES (1, 1.0), (2, 2.0)",
    ),
    _shape(
        "column_defaults",
        "CREATE TABLE {t} (id BIGINT, status STRING DEFAULT 'new') "
        "TBLPROPERTIES ('delta.feature.allowColumnDefaults'='supported')",
        "INSERT INTO {t} (id) VALUES (1), (2)",
    ),
    _shape(
        "type_widening",
        "CREATE TABLE {t} (id INT, amount FLOAT) TBLPROPERTIES ('delta.enableTypeWidening'='true')",
        "INSERT INTO {t} VALUES (1, 1.5), (2, 2.5)",
        "ALTER TABLE {t} ALTER COLUMN id TYPE BIGINT",
        "ALTER TABLE {t} ALTER COLUMN amount TYPE DOUBLE",
        "INSERT INTO {t} VALUES (3000000000, 3.25)",
    ),
    _shape(
        "variant",
        "CREATE TABLE {t} (id BIGINT, v VARIANT)",
        "INSERT INTO {t} VALUES (1, PARSE_JSON('{{\"a\": 1}}')), (2, PARSE_JSON('\"s\"'))",
    ),
    _shape(
        "variant_shredded",
        "CREATE TABLE {t} (id BIGINT, v VARIANT) "
        "TBLPROPERTIES ('delta.enableVariantShredding'='true')",
        "INSERT INTO {t} VALUES (1, PARSE_JSON('{{\"a\": 1}}')), (2, PARSE_JSON('{{\"a\": 2}}'))",
        direct_read=None,
    ),
    _shape(
        "timestamp_ntz",
        "CREATE TABLE {t} (id BIGINT, t TIMESTAMP_NTZ)",
        "INSERT INTO {t} VALUES (1, TIMESTAMP_NTZ'2026-01-01 10:00:00'), (2, NULL)",
    ),
    _shape(
        "collation",
        "CREATE TABLE {t} (id BIGINT, name STRING COLLATE UTF8_LCASE)",
        "INSERT INTO {t} VALUES (1, 'Oslo'), (2, 'oslo'), (3, 'LIMA')",
        # Byte comparison would find one row; the collation finds two.
        predicate="name = 'oslo'",
        tags=frozenset({"collated"}),
    ),
    _shape(
        "v2_checkpoint",
        f"CREATE TABLE {{t}} {_BASE} TBLPROPERTIES ('delta.checkpointPolicy'='v2', "
        "'delta.checkpointInterval'='2')",
        _ins(),
        _ins(),
        _ins(),
        "DELETE FROM {t} WHERE id = 1",
    ),
    _shape(
        "uniform_iceberg",
        f"CREATE TABLE {{t}} {_BASE} TBLPROPERTIES ('delta.enableIcebergCompatV2'='true', "
        "'delta.universalFormat.enabledFormats'='iceberg', "
        "'delta.enableDeletionVectors'='false', 'delta.columnMapping.mode'='name')",
        _ins(),
    ),
    _shape(
        "in_commit_timestamps",
        f"CREATE TABLE {{t}} {_BASE} TBLPROPERTIES ('delta.enableInCommitTimestamps'='true')",
        _ins(),
    ),
    _shape(
        "checkpoint_protection",
        f"CREATE TABLE {{t}} {_BASE} TBLPROPERTIES ('delta.enableRowTracking'='false')",
        _ins(),
        "DELETE FROM {t} WHERE id = 3",
        "ALTER TABLE {t} DROP FEATURE deletionVectors",
    ),
    _shape(
        "nested_types",
        "CREATE TABLE {t} (id BIGINT, s STRUCT<a: INT, b: STRING>, arr ARRAY<INT>, "
        "m MAP<STRING, INT>, dec DECIMAL(38, 9), bin BINARY, b BOOLEAN)",
        "INSERT INTO {t} VALUES (1, named_struct('a', 1, 'b', 'x'), array(1, 2), map('k', 1), "
        "12345678901234567890.123456789, X'CAFE', true), "
        "(2, NULL, NULL, NULL, NULL, NULL, NULL)",
    ),
    _shape(
        "row_filter",
        f"CREATE TABLE {{t}} {_BASE}",
        _ins(),
        "CREATE OR REPLACE FUNCTION {t}_rf(city STRING) RETURN city <> 'oslo'",
        "ALTER TABLE {t} SET ROW FILTER {t}_rf ON (city)",
        direct_read=False,
        time_travel=False,
    ),
    _shape(
        "column_mask",
        f"CREATE TABLE {{t}} {_BASE}",
        _ins(),
        "CREATE OR REPLACE FUNCTION {t}_mask(city STRING) RETURN '***'",
        "ALTER TABLE {t} ALTER COLUMN city SET MASK {t}_mask",
        direct_read=False,
        time_travel=False,
    ),
    _shape(
        "geospatial",
        "CREATE TABLE {t} (id BIGINT, g GEOMETRY(4326))",
        "INSERT INTO {t} VALUES (1, ST_GeomFromText('POINT(1 2)', 4326))",
        direct_read=False,
    ),
    _shape(
        "catalog_managed",
        f"CREATE TABLE {{t}} {_BASE} TBLPROPERTIES ('delta.feature.catalogManaged'='supported')",
        _ins(),
    ),
    _shape("empty", f"CREATE TABLE {{t}} {_BASE}"),
]
BY_NAME = {s.name: s for s in SHAPES}


# ------------------------------------------------------------------ plumbing


class Warehouse:
    """Ground truth: what Databricks itself says is in the table."""

    def __init__(self, workspace: Any, warehouse_id: str) -> None:
        self.workspace = workspace
        self.warehouse_id = warehouse_id

    def run(self, sql: str) -> Any:
        api = self.workspace.statement_execution
        r = api.execute_statement(warehouse_id=self.warehouse_id, statement=sql, wait_timeout="50s")
        while r.status.state.value in ("PENDING", "RUNNING"):
            time.sleep(1)
            r = api.get_statement(r.statement_id)
        if r.status.error:
            raise RuntimeError(f"{sql[:80]!r}: {r.status.error.message}")
        return r

    def rows(self, sql: str) -> list[list[Any]]:
        r = self.run(sql)
        return (r.result.data_array or []) if r.result else []

    def count(self, name: str, where: str | None = None, suffix: str = "") -> int:
        clause = f" WHERE {where}" if where else ""
        return int(self.rows(f"SELECT count(*) FROM {name}{suffix}{clause}")[0][0])

    def columns(self, name: str) -> list[str]:
        return [c.name for c in self.run(f"SELECT * FROM {name} LIMIT 0").manifest.schema.columns]

    def ids(self, name: str) -> list[int]:
        return sorted(int(r[0]) for r in self.rows(f"SELECT id FROM {name}") if r[0] is not None)


@pytest.fixture(scope="session")
def matrix_enabled(live_config: Any) -> None:
    if os.environ.get("DELTASWAMP_TEST_MATRIX", "").lower() not in ("1", "true", "yes"):
        pytest.skip("the shape matrix is opt-in: set DELTASWAMP_TEST_MATRIX=1")
    if not live_config.warehouse_id:
        pytest.skip("DELTASWAMP_TEST_WAREHOUSE_ID is required to build the shapes")


@pytest.fixture(scope="session")
def warehouse(matrix_enabled: None, live_config: Any, live_workspace: Any) -> Warehouse:
    return Warehouse(live_workspace, live_config.warehouse_id)


@pytest.fixture(scope="session")
def built(warehouse: Warehouse, live_config: Any) -> Any:
    """Build every shape once, in parallel, and drop them all afterwards.

    Yields {shape name: fully qualified table name, or the build error}. A shape
    the workspace cannot create (a preview that is off) is skipped, not failed.
    """
    run_id = uuid.uuid4().hex[:8]
    names = {s.name: f"{live_config.prefix}.dsm_{run_id}_{s.name}" for s in SHAPES}

    def build(shape: Shape) -> tuple[str, str | None]:
        full = names[shape.name]
        try:
            for statement in shape.statements:
                warehouse.run(statement.format(t=full))
        except Exception as exc:
            return shape.name, str(exc)[:300]
        return shape.name, None

    with concurrent.futures.ThreadPoolExecutor(8) as pool:
        errors = dict(pool.map(build, SHAPES))
    try:
        yield {n: (names[n] if errors[n] is None else RuntimeError(errors[n])) for n in names}
    finally:
        for shape in SHAPES:
            with contextlib.suppress(Exception):
                warehouse.run(f"DROP TABLE IF EXISTS {names[shape.name]}")
            for suffix in ("_rf", "_mask"):
                with contextlib.suppress(Exception):
                    warehouse.run(f"DROP FUNCTION IF EXISTS {names[shape.name]}{suffix}")


@pytest.fixture(scope="session")
def staging_volume(warehouse: Warehouse, live_config: Any) -> Any:
    volume = f"{live_config.prefix}.dsm_staging"
    warehouse.run(f"CREATE VOLUME IF NOT EXISTS {volume}")
    yield volume


@pytest.fixture(scope="session")
def direct(live_config: Any) -> Any:
    return ds.connect(host=live_config.host, token=live_config.token)


@pytest.fixture(scope="session")
def fallback(live_config: Any, staging_volume: str) -> Any:
    return ds.connect(
        host=live_config.host,
        token=live_config.token,
        allow_sql_fallback=True,
        warehouse_id=live_config.warehouse_id,
        staging_volume=staging_volume,
    )


def _table_for(built: dict[str, Any], shape: Shape) -> str:
    name = built[shape.name]
    if isinstance(name, Exception):
        pytest.skip(f"this workspace cannot build {shape.name}: {name}")
    return str(name)


def _ids(table: Any) -> list[int] | None:
    if "id" not in table.column_names:
        return None
    return sorted(x for x in table.column("id").to_pylist() if x is not None)


def _agrees(got: Any, warehouse: Warehouse, name: str) -> None:
    assert got.num_rows == warehouse.count(name)
    assert got.column_names == warehouse.columns(name)
    ids = _ids(got)
    if ids is not None:
        assert ids == warehouse.ids(name)


shapes = pytest.mark.parametrize("shape", SHAPES, ids=[s.name for s in SHAPES])


# --------------------------------------------------------------------- reads


class TestReads:
    @shapes
    def test_direct_read_agrees_or_refuses(
        self, shape: Shape, built: Any, direct: Any, warehouse: Warehouse
    ) -> None:
        """A direct engine either reads exactly what Databricks sees, or says why not."""
        name = _table_for(built, shape)
        table = direct.table(name)
        verdict = table.can(Operation.SCAN)
        if shape.direct_read is None:
            if verdict.ok:
                try:
                    got = pa.table(table.to_arrow())
                except Exception as exc:
                    assert str(exc), "a failed read must say why"
                    return
                _agrees(got, warehouse, name)
            return
        assert verdict.ok is shape.direct_read, verdict
        if verdict.ok:
            _agrees(pa.table(table.to_arrow()), warehouse, name)
        else:
            assert verdict.reason

    @shapes
    def test_fallback_read_agrees(
        self, shape: Shape, built: Any, fallback: Any, warehouse: Warehouse
    ) -> None:
        name = _table_for(built, shape)
        _agrees(pa.table(fallback.table(name).to_arrow()), warehouse, name)

    @shapes
    def test_predicate_agrees(
        self, shape: Shape, built: Any, fallback: Any, warehouse: Warehouse
    ) -> None:
        name = _table_for(built, shape)
        if shape.predicate is None:
            pytest.skip("no predicate for this shape")
        got = pa.table(fallback.table(name).to_arrow(predicate=shape.predicate)).num_rows
        assert got == warehouse.count(name, shape.predicate)

    @shapes
    def test_time_travel_to_the_first_version(
        self, shape: Shape, built: Any, fallback: Any, warehouse: Warehouse
    ) -> None:
        name = _table_for(built, shape)
        if not shape.time_travel:
            verdict = fallback.table(name).can(Operation.TIME_TRAVEL)
            assert not verdict.ok
            assert "row filter" in verdict.reason or "column mask" in verdict.reason
            return
        want = warehouse.count(name, suffix=" VERSION AS OF 0")
        assert pa.table(fallback.table(name).to_arrow(version=0)).num_rows == want

    @shapes
    def test_claimed_log_reads_work(self, shape: Shape, built: Any, fallback: Any) -> None:
        """If deltaswamp says it can, it must -- the claim is the contract."""
        name = _table_for(built, shape)
        table = fallback.table(name)
        for op, call in (
            (Operation.HISTORY, table.history),
            (Operation.DETAIL, table.detail),
            (Operation.FILES, table.files),
        ):
            verdict = table.can(op)
            if verdict.ok:
                call()
            else:
                assert verdict.reason, f"{op.value} refused silently"

    @shapes
    def test_features_match_describe_detail(
        self, shape: Shape, built: Any, fallback: Any, warehouse: Warehouse
    ) -> None:
        import json

        name = _table_for(built, shape)
        r = warehouse.run(f"DESCRIBE DETAIL {name}")
        detail = dict(
            zip([c.name for c in r.manifest.schema.columns], r.result.data_array[0], strict=True)
        )
        want = set(json.loads(detail["tableFeatures"] or "[]"))
        got = set(fallback.table(name).features())
        # A legacy protocol implies its features rather than listing them.
        if int(detail["minWriterVersion"]) < 7:
            assert got <= want
        else:
            assert got == want

    def test_change_data_feed_agrees(self, built: Any, fallback: Any, warehouse: Warehouse) -> None:
        name = _table_for(built, BY_NAME["change_data_feed"])
        table = fallback.table(name)
        assert table.can(Operation.CDF).engine is Engine.KERNEL
        got = pa.table(table.cdf(starting_version=0)).num_rows
        assert got == warehouse.count(f"table_changes('{name}', 0)")

    def test_collated_predicates_never_go_direct(self, built: Any, direct: Any) -> None:
        """Byte comparison gives a wrong answer here, not an error."""
        name = _table_for(built, BY_NAME["collation"])
        with pytest.raises(ds.DeltaSwampError, match="collat"):
            direct.table(name).to_arrow(predicate="name = 'oslo'")

    def test_masks_and_filters_are_applied(self, built: Any, fallback: Any) -> None:
        masked = pa.table(fallback.table(_table_for(built, BY_NAME["column_mask"])).to_arrow())
        assert set(masked.column("city").to_pylist()) == {"***"}
        filtered = pa.table(fallback.table(_table_for(built, BY_NAME["row_filter"])).to_arrow())
        assert "oslo" not in filtered.column("city").to_pylist()


# -------------------------------------------------------------------- writes

writable = pytest.mark.parametrize(
    "shape", [s for s in SHAPES if s.writes], ids=[s.name for s in SHAPES if s.writes]
)


class TestWrites:
    """Managed tables grant no external writes, so these go through the warehouse."""

    @writable
    def test_append_delete_update_merge(
        self, shape: Shape, built: Any, fallback: Any, warehouse: Warehouse
    ) -> None:
        name = _table_for(built, shape)
        table = fallback.table(name)
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            before = warehouse.count(name)
            batch = pa.table(table.head(2))
            table.append(batch)
            assert warehouse.count(name) == before + batch.num_rows

            target = warehouse.ids(name)[0]
            gone = warehouse.count(name, f"id = {target}")
            table.delete(f"id = {target}")
            assert warehouse.count(name) == before + batch.num_rows - gone

            table.update(updates={"id": "id + 1000000"}, predicate="id < 3")
            moved = warehouse.count(name, "id >= 1000000")
            assert warehouse.count(name) == before + batch.num_rows - gone

            source = pa.table(table.head(1))
            (
                table.merge(source, "target.id = source.id")
                .when_matched_update_all()
                .when_not_matched_insert_all()
                .execute()
            )
            assert warehouse.count(name) == before + batch.num_rows - gone
            assert warehouse.count(name, "id >= 1000000") == moved

    @writable
    def test_maintenance_and_ddl(
        self, shape: Shape, built: Any, fallback: Any, warehouse: Warehouse
    ) -> None:
        name = _table_for(built, shape)
        table = fallback.table(name)
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            table.optimize()
            table.vacuum(dry_run=True)
            if "clustered" in shape.tags:
                assert not table.can(Operation.ZORDER).ok
            else:
                table.z_order(["id"])
            table.add_column({"dsm_extra": "STRING"})
            assert "dsm_extra" in warehouse.columns(name)
            table.set_properties({"deltaswamp.matrix": "yes"})
            props = {r[0]: r[1] for r in warehouse.rows(f"SHOW TBLPROPERTIES {name}")}
            assert props.get("deltaswamp.matrix") == "yes"
            table.unset_properties(["deltaswamp.matrix"])
            table.set_comment("matrix")
            if table.can(Operation.DROP_COLUMN).ok:
                table.drop_column("dsm_extra")

    @writable
    def test_restore(self, shape: Shape, built: Any, fallback: Any, warehouse: Warehouse) -> None:
        name = _table_for(built, shape)
        table = fallback.table(name)
        want = warehouse.count(name, suffix=" VERSION AS OF 1")
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            table.restore(1)
        assert warehouse.count(name) == want
        assert pa.table(fallback.table(name).to_arrow()).num_rows == want
