"""Regressions for the write-path audit that need no real table.

Each test failed before its fix.
"""

from __future__ import annotations

import datetime as dt
import json
from typing import Any

import pytest

pa = pytest.importorskip("pyarrow")

from deltaswamp.engine import metadata as m  # noqa: E402
from deltaswamp.errors import InvalidArgumentError, UnreachableTableError  # noqa: E402

from tests.helpers import resolved_table as table  # noqa: E402
from tests.unit.sql_fakes import engine  # noqa: E402

GENERATED = {"delta.generationExpression": "id * 2"}
IDENTITY = {
    "delta.identity.start": "10",
    "delta.identity.step": "5",
    "delta.identity.allowExplicitInsert": "false",
}


class TestManagedCreateDdl:
    """LW-8: the warehouse CREATE TABLE dropped every column clause but NOT NULL."""

    def test_generated_identity_default_and_comment_are_emitted(self) -> None:
        eng, rec, _ = engine()
        schema = pa.schema(
            [
                pa.field("id", pa.int64(), nullable=False, metadata={"comment": "it's"}),
                pa.field("g", pa.int64(), metadata=GENERATED),
                pa.field("i", pa.int64(), metadata=IDENTITY),
                pa.field("d", pa.string(), metadata={"CURRENT_DEFAULT": "'x'"}),
            ]
        )
        eng.create_managed("main.s.t", schema)
        assert rec.last == (
            "CREATE TABLE `main`.`s`.`t` ("
            "`id` BIGINT NOT NULL COMMENT 'it\\'s', "
            "`g` BIGINT GENERATED ALWAYS AS (id * 2), "
            "`i` BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 10 INCREMENT BY 5), "
            "`d` STRING DEFAULT 'x') USING DELTA"
            " TBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported')"
        )

    def test_explicit_insert_identity_is_by_default(self) -> None:
        eng, rec, _ = engine()
        md = {**IDENTITY, "delta.identity.allowExplicitInsert": "true"}
        eng.create_managed("main.s.t", pa.schema([pa.field("i", pa.int64(), metadata=md)]))
        assert "GENERATED BY DEFAULT AS IDENTITY (START WITH 10 INCREMENT BY 5)" in rec.last

    def test_nested_not_null_is_kept(self) -> None:
        eng, rec, _ = engine()
        inner = pa.struct([pa.field("a", pa.int32(), nullable=False), ("b", pa.string())])
        eng.create_managed("main.s.t", pa.schema([("s", inner)]))
        assert "`s` STRUCT<`a`: INT NOT NULL, `b`: STRING>" in rec.last

    def test_an_expression_cannot_end_the_statement(self) -> None:
        eng, _, _ = engine()
        md = {"delta.generationExpression": "1); DROP TABLE x; --"}
        with pytest.raises(InvalidArgumentError, match="single SQL expression"):
            eng.create_managed("main.s.t", pa.schema([pa.field("g", pa.int64(), metadata=md)]))

    def test_invariants_are_refused_rather_than_dropped(self) -> None:
        eng, rec, _ = engine()
        md = {"delta.invariants": json.dumps({"expression": {"expression": "g > 0"}})}
        with pytest.raises(UnreachableTableError, match="CHECK constraint"):
            eng.create_managed("main.s.t", pa.schema([pa.field("g", pa.int64(), metadata=md)]))
        assert not any(s.startswith("CREATE") for s in rec.sql)


class TestStagingRebase:
    """LC-03: staged Parquet was read with Spark's legacy Julian rebase."""

    def test_read_files_is_told_the_file_is_proleptic_gregorian(self) -> None:
        eng, rec, _ = engine()
        eng.append(table(), pa.table({"d": pa.array([dt.date(1, 1, 1)], pa.date32())}))
        assert "datetimeRebaseMode => 'CORRECTED'" in rec.last
        assert "int96RebaseMode => 'CORRECTED'" in rec.last

    def test_sub_microsecond_timestamps_raise_a_library_error(self) -> None:
        eng, _, _ = engine()
        data = pa.table({"ts": pa.array([1_000_000_001], pa.timestamp("ns", "UTC"))})
        with pytest.raises(InvalidArgumentError, match="sub-microsecond"):
            eng.append(table(), data)


class TestVersionZeroFeatures:
    """LW-1/LW-2 for the catalog staging create: column metadata named no feature."""

    def _protocol(self, metadata: dict[str, str]) -> dict[str, Any]:
        schema = {
            "type": "struct",
            "fields": [
                {"name": "id", "type": "long", "nullable": True, "metadata": {}},
                {"name": "g", "type": "long", "nullable": True, "metadata": metadata},
            ],
        }
        actions = [
            json.loads(a)
            for a in m.initial_actions(
                table_id="tid",
                schema=schema,
                required_protocol={},
                configuration={},
                engine_info="t",
                now_ms=1,
            )
        ]
        found: dict[str, Any] = next(a["protocol"] for a in actions if "protocol" in a)
        return found

    @pytest.mark.parametrize(
        ("metadata", "feature"),
        [
            (GENERATED, "generatedColumns"),
            (IDENTITY, "identityColumns"),
            ({"CURRENT_DEFAULT": "1"}, "allowColumnDefaults"),
        ],
    )
    def test_the_feature_is_declared(self, metadata: dict[str, str], feature: str) -> None:
        assert feature in self._protocol(metadata)["writerFeatures"]


class TestSqlTypeNames:
    """OC-8: add_column({"x": "bigint"}) was a Delta type on one engine only."""

    @pytest.mark.parametrize(
        ("text", "delta"),
        [
            ("bigint", "long"),
            ("INT", "integer"),
            ("varchar(10)", "string"),
            ("numeric(10, 2)", "decimal(10,2)"),
            ("array<int>", {"type": "array", "elementType": "integer", "containsNull": True}),
            (
                "map<string, bigint>",
                {
                    "type": "map",
                    "keyType": "string",
                    "valueType": "long",
                    "valueContainsNull": True,
                },
            ),
            (
                "struct<a:int, b: array<string>>",
                {
                    "type": "struct",
                    "fields": [
                        {"name": "a", "type": "integer", "nullable": True, "metadata": {}},
                        {
                            "name": "b",
                            "type": {
                                "type": "array",
                                "elementType": "string",
                                "containsNull": True,
                            },
                            "nullable": True,
                            "metadata": {},
                        },
                    ],
                },
            ),
        ],
    )
    def test_sql_spellings_parse(self, text: str, delta: Any) -> None:
        assert m.sql_type_to_delta(text) == delta

    @pytest.mark.parametrize("text", ["int64x", "array<int", "decimal(99,1)", "map<int>"])
    def test_nonsense_is_refused(self, text: str) -> None:
        with pytest.raises(ValueError):
            m.sql_type_to_delta(text)


class TestWithoutPyarrow:
    """OC-10/OC-11: a missing pyarrow surfaced as a raw ModuleNotFoundError."""

    @pytest.fixture
    def no_pyarrow(self, monkeypatch: Any) -> None:
        import sys

        monkeypatch.setitem(sys.modules, "pyarrow", None)

    def test_list_schema_names_the_extra(self, no_pyarrow: None) -> None:
        from deltaswamp.connection import _schema_arg

        with pytest.raises(ImportError, match=r"deltaswamp\[pyarrow\]"):
            _schema_arg([("id", "long")])

    def test_delta_rs_dml_names_the_extra(self, no_pyarrow: None) -> None:
        from deltaswamp.engine.deltars import _datafusion_predicate, _datafusion_updates

        with pytest.raises(ImportError, match=r"deltaswamp\[pyarrow\]"):
            _datafusion_predicate(object(), "id = 1", dml="delete")
        with pytest.raises(ImportError, match=r"deltaswamp\[pyarrow\]"):
            _datafusion_updates(object(), {"id": "2"}, rendered=False)

    def test_plan_scan_names_the_extra(self, no_pyarrow: None) -> None:
        from deltaswamp.engine.kernel import KernelEngine

        with pytest.raises(ImportError, match=r"deltaswamp\[pyarrow\]"):
            KernelEngine().plan_scan(table())

    def test_iceberg_is_unavailable(self, no_pyarrow: None) -> None:
        from deltaswamp.engine.iceberg import IcebergEngine

        assert not IcebergEngine.available()

    def test_extras_that_convert_through_arrow_pull_it_in(self) -> None:
        import pathlib
        import tomllib

        root = pathlib.Path(__file__).resolve().parents[2]
        extras = tomllib.loads((root / "pyproject.toml").read_text())["project"][
            "optional-dependencies"
        ]
        for extra in ("pandas", "polars", "iceberg"):
            assert any(d.startswith("pyarrow") for d in extras[extra]), extra
