"""Column values a kernel write computes and checks itself.

delta-kernel 0.28 refuses to write a table whose schema uses generated
columns, identity columns or column invariants. Spark computes and checks
these as it writes each row; the kernel write paths here do the same, over
every batch before it reaches the native writer, and then tell the commit
which features they stood in for (``values_checked=``, `crate::restate`):

* A **generated column** the data leaves out is computed from its generation
  expression; one the data gives is checked to equal it (null-safe), as
  Spark's ``g <=> expr`` constraint does. Values are stored as Spark stores
  an expression's result into the column's type.
* An **identity column** the data leaves out is filled from a block of values
  the table's high-water mark already covers (`IdentityBlock`): reserved by
  the commit itself for a local append, and by a metadata-only commit before
  the job for a distributed one, so workers need no coordination and the
  data commit changes no metadata. A value the data gives is refused for
  GENERATED ALWAYS, and kept for GENERATED BY DEFAULT without moving the
  high-water mark -- as Spark does; ``ALTER TABLE ... SYNC IDENTITY`` exists
  for exactly that.
* A **column invariant** is a CHECK over the row: evaluated with the table's
  CHECK constraints (`constraints.ConstraintCheck`).
* A left-out column with a literal **DEFAULT** gets it, as `Table.append`
  gives it.

Expressions are Spark SQL, respelled for DuckDB and evaluated in the sandboxed
in-memory DuckDB `engine.duckfilter` sets up. One DuckDB cannot evaluate as
Databricks does is refused when the write is planned, never partway through.
"""

from __future__ import annotations

import importlib.util
import json
import threading
from collections.abc import Iterator, Mapping
from dataclasses import dataclass, field
from typing import Any

from ..errors import EngineLimitError, InvalidArgumentError

__all__ = [
    "IdentityBlock",
    "IdentityCursor",
    "IdentitySpec",
    "TableValues",
    "ValueWriter",
    "reserve_identity",
]

_GENERATION = "delta.generationExpression"
_INVARIANTS = "delta.invariants"
_IDENTITY_START = "delta.identity.start"
_IDENTITY_STEP = "delta.identity.step"
_IDENTITY_HWM = "delta.identity.highWaterMark"
_IDENTITY_EXPLICIT = "delta.identity.allowExplicitInsert"
_DEFAULT = "CURRENT_DEFAULT"

_INT64 = (-(2**63), 2**63 - 1)


@dataclass(frozen=True)
class IdentitySpec:
    """One identity column, as its field metadata declares it."""

    name: str
    start: int
    step: int
    high_water_mark: int | None
    #: GENERATED BY DEFAULT: the data may give values of its own.
    allow_explicit: bool

    def first_free(self) -> int:
        """The first value no writer has generated yet, as Delta Spark computes it.

        The value after the high-water mark, rounded up (in the step's
        direction) to the next ``start + k * step``: a mark another writer left
        off that sequence must not put generated values off it. A mark before
        ``start`` counts for nothing (Spark replaces it), so generation begins
        at ``start``.
        """
        mark = self.high_water_mark
        if mark is None or (mark < self.start if self.step > 0 else mark > self.start):
            return self.start
        return round_to_next(self.start, self.step, mark + self.step)


def round_to_next(start: int, step: int, value: int) -> int:
    """`value`, or the next ``start + k * step`` after it in the step's direction.

    Delta Spark's ``IdentityColumn.roundToNext``, with Java's truncating
    division: a value on the start's wrong side rounds towards it, never past.
    """
    offset = value - start
    if offset % step == 0:
        return value
    quotient = abs(offset) // abs(step) * (1 if (offset >= 0) == (step > 0) else -1)
    if (offset > 0) == (step > 0):
        quotient += 1
    return start + step * quotient


@dataclass(frozen=True)
class IdentityBlock:
    """Values ``first, first + step, ...`` of one identity column, `count` of them,
    that the table's high-water mark already covers and nothing else will use."""

    first: int
    step: int
    count: int

    def slot(self, index: int, slots: int) -> IdentityBlock:
        """The `index`-th of `slots` equal, disjoint parts of this block."""
        if slots <= 0 or not 0 <= index < slots:
            raise InvalidArgumentError(
                f"identity slot {index} is outside the {slots} the write reserved"
            )
        size = self.count // slots
        return IdentityBlock(self.first + index * size * self.step, self.step, size)


class IdentityCursor:
    """The values of an `IdentityBlock` one writer has not used yet.

    Every `ValueWriter` that draws from one cursor takes values after the last
    one taken, so several writes by one worker task (a Ray write task calls
    `WritePlan.write` once per block) never repeat a value.
    """

    def __init__(self, block: IdentityBlock) -> None:
        import threading

        self.block = block
        self.used = 0
        self._lock = threading.Lock()

    def take(self, name: str, rows: int) -> int:
        """The first of `rows` fresh values; refused when the block runs out."""
        with self._lock:
            if self.used + rows > self.block.count:
                raise InvalidArgumentError(
                    f"identity column {name}: this write reserved {self.block.count} values "
                    f"per task, and the task's data holds more rows than that "
                    f"({self.used + rows}); plan with a larger identity_rows_per_task"
                )
            first = self.block.first + self.used * self.block.step
            self.used += rows
            return first


#: Cursors of the identity slots this process writes, by (plan, task, column).
_CURSORS: dict[tuple[str, int, str], IdentityCursor] = {}
_CURSORS_LOCK = threading.Lock()


def slot_cursor(plan: str, task: int, name: str, block: IdentityBlock) -> IdentityCursor:
    """The process's cursor over `block`, the slot of task `task` of plan `plan`."""
    with _CURSORS_LOCK:
        cursor = _CURSORS.get((plan, task, name))
        if cursor is None or cursor.block != block:
            cursor = _CURSORS[(plan, task, name)] = IdentityCursor(block)
        return cursor


@dataclass(frozen=True)
class TableValues:
    """What a table's schema asks a writer to compute or check."""

    #: Top-level generated columns, name -> Spark SQL generation expression.
    generated: dict[str, str] = field(default_factory=dict)
    #: Top-level identity columns, by name.
    identity: dict[str, IdentitySpec] = field(default_factory=dict)
    #: Column invariants, dotted column path -> Spark SQL boolean expression.
    invariants: dict[str, str] = field(default_factory=dict)
    #: Generation expressions or identity declarations on nested fields,
    #: which Delta does not define and nothing here computes.
    nested: tuple[str, ...] = ()
    #: Invariant metadata that could not be read.
    unreadable: tuple[str, ...] = ()

    @classmethod
    def of(cls, schema: Mapping[str, Any] | str | None) -> TableValues:
        """The values `schema` (a Delta schema, or its JSON text) declares."""
        parsed: Mapping[str, Any] = (
            json.loads(schema) if isinstance(schema, str) else (schema or {})
        )
        generated: dict[str, str] = {}
        identity: dict[str, IdentitySpec] = {}
        invariants: dict[str, str] = {}
        nested: list[str] = []
        unreadable: list[str] = []

        def walk(fields: Any, path: tuple[str, ...]) -> None:
            for f in fields or ():
                if not isinstance(f, dict):
                    continue
                name = str(f.get("name"))
                here = (*path, name)
                dotted = ".".join(here)
                meta = f.get("metadata") or {}
                if _GENERATION in meta or _IDENTITY_START in meta:
                    if path:
                        nested.append(dotted)
                    elif _GENERATION in meta:
                        generated[name] = str(meta[_GENERATION])
                    else:
                        identity[name] = _identity_spec(name, meta)
                if _INVARIANTS in meta:
                    try:
                        raw = meta[_INVARIANTS]
                        parsed = json.loads(raw) if isinstance(raw, str) else raw
                        invariants[dotted] = str(parsed["expression"]["expression"])
                    except (ValueError, TypeError, KeyError):
                        unreadable.append(dotted)
                for child in _struct_fields(f.get("type")):
                    walk(child, here)

        walk(parsed.get("fields"), ())
        return cls(generated, identity, invariants, tuple(nested), tuple(unreadable))

    def __bool__(self) -> bool:
        return bool(self.generated or self.identity or self.invariants or self.nested)

    def features(self) -> list[str]:
        """The features a write that computed these values stands in for."""
        out = []
        if self.generated:
            out.append("generatedColumns")
        if self.identity:
            out.append("identityColumns")
        if self.invariants:
            out.append("invariants")
        return out

    def refusal(self, arrow_schema: Any) -> str | None:
        """Why a kernel write cannot compute or check these values here, if it cannot.

        Settled before anything is written: an expression DuckDB cannot
        evaluate as Databricks does, or one that does not bind over the
        table's columns, is refused now rather than by the first worker.
        """
        if self.nested:
            return (
                f"the table declares a generated or identity column on a nested field "
                f"({', '.join(self.nested)}), which Delta does not define for writers"
            )
        if self.unreadable:
            return f"the table's invariant on {', '.join(self.unreadable)} cannot be read"
        for spec in self.identity.values():
            if spec.step == 0:
                return f"identity column {spec.name} has step 0"
        expressions = list(self.generated.values()) + list(self.invariants.values())
        if not expressions:
            return None
        if (
            importlib.util.find_spec("duckdb") is None
            or importlib.util.find_spec("pyarrow") is None
        ):
            return (
                "the table has generated columns or column invariants, which the kernel write "
                "paths evaluate with DuckDB, and DuckDB is not installed "
                "(pip install 'deltaswamp[duckdb]')"
            )
        from .constraints import ConstraintCheck, duckdb_text

        for name, expression in sorted(self.generated.items()):
            what = f"generated column {name} ({expression})"
            try:
                projection = _Generator({name: expression}, arrow_schema)
            except EngineLimitError as exc:
                return f"{what} uses SQL DuckDB cannot evaluate as Databricks does ({exc.reason})"
            except Exception as exc:
                return f"{what} cannot be evaluated over the table's columns: {exc}"
            projection.close()
        for path, expression in sorted(self.invariants.items()):
            try:
                duckdb_text(expression)
                check = ConstraintCheck({f"invariant on {path}": expression}, arrow_schema, what="")
                check.bind()
                check.close()
            except EngineLimitError as exc:
                return (
                    f"the invariant on {path} ({expression}) uses SQL DuckDB cannot evaluate as "
                    f"Databricks does ({exc.reason})"
                )
            except Exception as exc:
                return f"the invariant on {path} ({expression}) cannot be evaluated: {exc}"
        return None

    def generates_identity(self, names: Any = None) -> list[str]:
        """The identity columns a write whose data has columns `names` must generate
        (all of them when the columns are not known)."""
        if names is None:
            return sorted(self.identity)
        present = {str(n).lower() for n in names}
        return sorted(n for n in self.identity if n.lower() not in present)


def _struct_fields(datatype: Any) -> Iterator[list[Any]]:
    """The field lists of every struct inside `datatype` (through arrays and maps)."""
    if isinstance(datatype, dict):
        kind = datatype.get("type")
        if kind == "struct":
            yield datatype.get("fields") or []
        elif kind == "array":
            yield from _struct_fields(datatype.get("elementType"))
        elif kind == "map":
            yield from _struct_fields(datatype.get("keyType"))
            yield from _struct_fields(datatype.get("valueType"))


def _identity_spec(name: str, meta: Mapping[str, Any]) -> IdentitySpec:
    def number(key: str, default: int | None) -> int | None:
        value = meta.get(key)
        return default if value is None else int(value)

    explicit = meta.get(_IDENTITY_EXPLICIT, False)
    if isinstance(explicit, str):
        explicit = explicit.lower() == "true"
    return IdentitySpec(
        name=name,
        start=int(number(_IDENTITY_START, 1) or 0),
        step=int(number(_IDENTITY_STEP, 1) or 0),
        high_water_mark=number(_IDENTITY_HWM, None),
        allow_explicit=bool(explicit),
    )


def reserve_identity(state: Any, counts: Mapping[str, int]) -> tuple[Any, dict[str, IdentityBlock]]:
    """The metadata change that moves each identity column's high-water mark past
    `counts[name]` new values, and the block of values each change reserves.

    A pure function of `state` (a `metadata.TableState`), so a commit that
    loses a race recomputes it against the winner's high-water mark.
    """
    from . import metadata as meta

    schema = state.schema
    blocks: dict[str, IdentityBlock] = {}
    for f in schema.get("fields") or ():
        name = f.get("name")
        count = int(counts.get(name, 0))
        if count <= 0:
            continue
        spec = _identity_spec(name, f.get("metadata") or {})
        first = spec.first_free()
        last = first + spec.step * (count - 1)
        if not (_INT64[0] <= first <= _INT64[1] and _INT64[0] <= last <= _INT64[1]):
            raise InvalidArgumentError(
                f"identity column {name} cannot take {count} more values: they would pass "
                "the range of a BIGINT"
            )
        f.setdefault("metadata", {})[_IDENTITY_HWM] = last
        blocks[name] = IdentityBlock(first, spec.step, count)
    missing = sorted(set(counts) - {f.get("name") for f in schema.get("fields") or ()})
    if missing:
        raise InvalidArgumentError(f"the table has no identity column {', '.join(missing)}")
    change = meta.Change(
        operation="CHANGE COLUMN",
        parameters={"reason": "reserve identity values"},
        metadata=meta._new_metadata(state, schema) if blocks else None,
    )
    return change, blocks


class _Generator:
    """Generation expressions evaluated per row, each stored as its column's type."""

    def __init__(self, expressions: Mapping[str, str], arrow_schema: Any) -> None:
        from .constraints import duckdb_text
        from .duckfilter import Projection

        self.names = {name: f"__deltaswamp_gen_{i}" for i, name in enumerate(expressions)}
        self.expressions = dict(expressions)
        self.projection = Projection(
            {self.names[n]: duckdb_text(text) for n, text in expressions.items()}, arrow_schema
        )

    def __call__(self, table: Any) -> dict[str, Any]:
        values = self.projection(table)
        return {name: values.column(alias) for name, alias in self.names.items()}

    def close(self) -> None:
        self.projection.close()


def _default_fills(pa: Any, table_schema: Any, present: set[str], rows: int) -> dict[str, Any]:
    """Literal DEFAULTs of the table columns the data leaves out, as `Table.append` fills them."""
    from ..table import _default_column

    fills = {}
    for f in table_schema:
        if f.name.lower() in present or not (f.metadata or {}).get(_DEFAULT.encode()):
            continue
        filled = _default_column(pa, f, rows)
        if filled is not None:
            fills[f.name] = filled
    return fills


class ValueWriter:
    """Batches as a kernel write commits them: defaults, identity values and
    generated columns filled in, generated values given checked, and every
    CHECK constraint and invariant evaluated.

    `table_schema` is the table's Arrow schema (with field metadata);
    `identity` the block (or the `IdentityCursor` over one) each identity
    column the data leaves out draws from.
    """

    def __init__(
        self,
        values: TableValues,
        table_schema: Any,
        constraints: Mapping[str, str],
        *,
        what: str,
        identity: Mapping[str, IdentityBlock | IdentityCursor] | None = None,
    ) -> None:
        from .constraints import ConstraintCheck

        self.values = values
        self.table_schema = table_schema
        self.what = what
        self.identity = {
            name: block if isinstance(block, IdentityCursor) else IdentityCursor(block)
            for name, block in (identity or {}).items()
        }
        checks = dict(constraints)
        for path, expression in values.invariants.items():
            checks[f"invariant on {path}"] = expression
        self.check = ConstraintCheck(checks, table_schema, what=what) if checks else None
        self.generator = _Generator(values.generated, table_schema) if values.generated else None

    def _field(self, name: str) -> Any:
        return self.table_schema.field(self.table_schema.get_field_index(name))

    def _identity_values(self, name: str, rows: int) -> Any:
        import pyarrow as pa

        cursor = self.identity.get(name)
        if cursor is None:
            raise InvalidArgumentError(
                f"the data leaves out identity column {name}, and this write reserved no "
                "values for it (plan_write(identity_tasks=...) reserves them; plan.write(data, "
                "task_index=...) draws from them)"
            )
        step = cursor.block.step
        first = cursor.take(name, rows) if rows else cursor.block.first
        values = pa.array(range(first, first + rows * step, step), pa.int64())
        return values.cast(self._field(name).type)

    def shape(self, batch: Any) -> Any:
        """`batch` completed and checked, ready to write."""
        import pyarrow as pa
        import pyarrow.compute as pc

        from .kernel_merge import store_cast

        table = batch if isinstance(batch, pa.Table) else pa.Table.from_batches([batch])
        rows = table.num_rows
        present = {n.lower() for n in table.column_names}
        by_lower = {n.lower(): n for n in table.column_names}

        for name, spec in sorted(self.values.identity.items()):
            if name.lower() in present:
                if not spec.allow_explicit:
                    raise InvalidArgumentError(
                        f"the data gives values for {name}, a GENERATED ALWAYS AS IDENTITY "
                        "column, which Delta generates itself "
                        "(DELTA_IDENTITY_COLUMNS_EXPLICIT_INSERT_NOT_SUPPORTED)"
                    )
                continue
            table = table.append_column(self._field(name), self._identity_values(name, rows))
        present = {n.lower() for n in table.column_names}

        exempt = {n.lower() for n in self.values.generated} | {
            n.lower() for n in self.values.identity
        }
        for name, filled in _default_fills(pa, self.table_schema, present | exempt, rows).items():
            table = table.append_column(self._field(name), filled)

        if self.generator is not None and rows:
            # Over the row as it will be written: every other column filled.
            complete = self._completed(table)
            computed = self.generator(complete)
            for name, raw in computed.items():
                target = self._field(name)
                value = store_cast(raw, target.type, name)
                given = by_lower.get(name.lower())
                if given is None:
                    table = table.append_column(target, value)
                    continue
                supplied = store_cast(table.column(given), target.type, name)
                same = pc.or_kleene(
                    pc.equal(supplied, value),
                    pc.and_(pc.is_null(supplied), pc.is_null(value)),
                )
                bad = pc.invert(pc.fill_null(same, False))
                if pc.any(bad).as_py():
                    index = pc.index(bad, True).as_py()
                    raise InvalidArgumentError(
                        f"the data violates generated column {name} "
                        f"({self.values.generated[name]}): {self.what} gives "
                        f"{supplied[index].as_py()!r} where the expression computes "
                        f"{value[index].as_py()!r}, so nothing was written "
                        "(DELTA_GENERATED_COLUMNS_VALUE_MISMATCH)"
                    )
        elif self.generator is not None:
            for name in self.values.generated:
                if name.lower() not in present:
                    target = self._field(name)
                    table = table.append_column(target, pa.array([], target.type))

        if self.check is not None:
            for chunk in table.to_batches():
                self.check.check(chunk)
        return table

    def _completed(self, table: Any) -> Any:
        """The row as the table will hold it, for expressions to read: every table
        column in the table's order and type, NULL where the data leaves it out
        (a generated column included, which no expression may read)."""
        import pyarrow as pa

        from .kernel_merge import store_cast

        by_lower = {n.lower(): n for n in table.column_names}
        columns = []
        for f in self.table_schema:
            given = by_lower.get(f.name.lower())
            columns.append(
                pa.nulls(table.num_rows, f.type)
                if given is None
                else store_cast(table.column(given), f.type, f.name)
            )
        return pa.Table.from_arrays(columns, schema=pa.schema(list(self.table_schema)))

    def output_schema(self, schema: Any) -> Any:
        """The schema `shape` gives batches of `schema`."""
        import pyarrow as pa

        return self.shape(pa.Table.from_batches([], schema=schema)).schema

    def shaped(self, reader: Any) -> Any:
        """`reader`, each batch shaped as it is read; checks close at its end."""
        import pyarrow as pa

        schema = self.output_schema(reader.schema)

        def batches() -> Iterator[Any]:
            try:
                for batch in reader:
                    yield from self.shape(batch).cast(schema).to_batches()
            finally:
                self.close()

        return pa.RecordBatchReader.from_batches(schema, batches())

    #: The name `constraints.ConstraintCheck` gives the same step.
    checked = shaped

    def close(self) -> None:
        if self.check is not None:
            self.check.close()
        if self.generator is not None:
            self.generator.close()
